x = 512
y = 10
label_offset = 19

slider_settings = {
    'harris': {"s1": {'pos': (x + 75, y + 80),
                      'range': (1, 20),
                      'tick_interval': 10,
                      'resolution': 1,
                      'label': 'Block Size',
                      'label_pos': (x + 65, y + label_offset + 80)},
               "s2": {'pos': (x + 75, y + 120),
                      'range': (1, 10),
                      'tick_interval': 5,
                      'resolution': 1,
                      'label': 'Kernel Size',
                      'label_pos': (x + 65, y + label_offset + 120)},
               "s3": {'pos': (x + 75, y + 160),
                      'range': (0.01, 1),
                      'tick_interval': 0.5,
                      'resolution': 0.01,
                      'label': 'K',
                      'label_pos': (x + 65, y + label_offset + 160)},
               },

    'shitomasi': {"s1": {'pos': (x + 75, y + 80),
                         'range': (1, 1000),
                         'tick_interval': 500,
                         'resolution': 1,
                         'label': 'Features',
                         'label_pos': (x + 65, y + label_offset + 80)},
                  "s2": {'pos': (x + 75, y + 120),
                         'range': (0, 1),
                         'tick_interval': 0.5,
                         'resolution': 0.01,
                         'label': 'Quality Control',
                         'label_pos': (x + 65, y + label_offset + 120)},
                  "s3": {'pos': (x + 75, y + 160),
                         'range': (10, 50),
                         'tick_interval': 25,
                         'resolution': 1,
                         'label': 'Min Distance',
                         'label_pos': (x + 65, y + label_offset + 160)},
                  },

    'sift': {"s1": {'pos': (x + 75, y + 80),
                    'range': (1, 1000),
                    'tick_interval': 500,
                    'resolution': 1,
                    'label': 'Features',
                    'label_pos': (x + 65, y + label_offset + 80)},
             "s2": {'pos': (x + 75, y + 120),
                    'range': (0, 1),
                    'tick_interval': 0.5,
                    'resolution': 0.01,
                    'label': 'Contrast Threshold',
                    'label_pos': (x + 65, y + label_offset + 120)},
             "s3": {'pos': (x + 75, y + 160),
                    'range': (1, 11),
                    'tick_interval': 5,
                    'resolution': 1,
                    'label': 'Octave Layers',
                    'label_pos': (x + 65, y + label_offset + 160)},
             },
    'fast': {"s1": {'pos': (x + 75, y + 80),
                    'range': (1, 21),
                    'tick_interval': 5,
                    'resolution': 1,
                    'label': 'Threshold',
                    'label_pos': (x + 65, y + label_offset + 80)},
             "s2": {'pos': (x + 75, y + 120),
                    'range': (0, 1),
                    'tick_interval': 1,
                    'resolution': 1,
                    'label': 'Non Max Suppression',
                    'label_pos': (x + 65, y + label_offset + 120)},
             },
    'orb': {"s1": {'pos': (x + 75, y + 80),
                   'range': (1, 1000),
                   'tick_interval': 500,
                   'resolution': 1,
                   'label': 'Features',
                   'label_pos': (x + 65, y + label_offset + 80)},
            "s2": {'pos': (x + 75, y + 120),
                   'range': (1, 2),
                   'tick_interval': 0.5,
                   'resolution': 0.1,
                   'label': 'Scale Factor',
                   'label_pos': (x + 65, y + label_offset + 120)},
            "s3": {'pos': (x + 75, y + 160),
                   'range': (1, 21),
                   'tick_interval': 1,
                   'resolution': 1,
                   'label': 'Levels',
                   'label_pos': (x + 65, y + label_offset + 160)},
            "s4": {'pos': (x + 75, y + 200),
                   'range': (1, 63),
                   'tick_interval': 32,
                   'resolution': 1,
                   'label': 'Edge Threshold',
                   'label_pos': (x + 65, y + label_offset + 200)},
            }
}

dropdown_settings = {
    'markers_list': {'pos': (x + 10, y),
                     },
    'aug_image': {'pos': (x + 150, y),
                  },
    'operation': {'pos': (x + 10, y+40),
                  },
    'algorithm': {'pos': (x + 150, y+40),
                  }

}
